/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppCategoryAttributes
 */
@JsonPropertyOrder({ AppCategoryAttributes.JSON_PROPERTY_PLATFORMS })

public class AppCategoryAttributes implements Serializable {

	private static final long serialVersionUID = 3771759234830305018L;

	public static final String JSON_PROPERTY_PLATFORMS = "platforms";

	private List<Platform> platforms = null;

	public AppCategoryAttributes addPlatformsItem(Platform platformsItem) {
		if (this.platforms == null) {
			this.platforms = new ArrayList<>();
		}
		this.platforms.add(platformsItem);
		return this;
	}

	/*
	 * 
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppCategoryAttributes appCategoryAttributes = (AppCategoryAttributes) o;
		return Objects.equals(this.platforms, appCategoryAttributes.platforms);
	}

	@Valid
	@JsonProperty(JSON_PROPERTY_PLATFORMS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public List<Platform> getPlatforms() {
		return this.platforms;
	}

	/*
	 * 
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return Objects.hash(this.platforms);
	}

	public AppCategoryAttributes platforms(List<Platform> platforms) {
		this.platforms = platforms;
		return this;
	}

	public void setPlatforms(List<Platform> platforms) {
		this.platforms = platforms;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/*
	 * 
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppCategoryAttributes {\n");
		sb.append("    platforms: ").append(toIndentedString(this.platforms)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
