/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppCategoryRelationshipsSubcategoriesLinks
 */
@JsonPropertyOrder({ AppCategoryRelationshipsSubcategoriesLinks.JSON_PROPERTY_SELF,
		AppCategoryRelationshipsSubcategoriesLinks.JSON_PROPERTY_RELATED })

public class AppCategoryRelationshipsSubcategoriesLinks implements Serializable {

	public static final String JSON_PROPERTY_RELATED = "related";

	public static final String JSON_PROPERTY_SELF = "self";

	private static final long serialVersionUID = 972900666632679941L;

	private String related;
	private String self;

	/*
	 *
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppCategoryRelationshipsSubcategoriesLinks appCategoryRelationshipsSubcategoriesLinks = (AppCategoryRelationshipsSubcategoriesLinks) o;
		return Objects.equals(this.self, appCategoryRelationshipsSubcategoriesLinks.self)
				&& Objects.equals(this.related, appCategoryRelationshipsSubcategoriesLinks.related);
	}

	@JsonProperty(JSON_PROPERTY_RELATED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getRelated() {
		return this.related;
	}

	@JsonProperty(JSON_PROPERTY_SELF)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getSelf() {
		return this.self;
	}

	/*
	 *
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return Objects.hash(this.self, this.related);
	}

	public AppCategoryRelationshipsSubcategoriesLinks related(String related) {
		this.related = related;
		return this;
	}

	public AppCategoryRelationshipsSubcategoriesLinks self(String self) {
		this.self = self;
		return this;
	}

	public void setRelated(String related) {
		this.related = related;
	}

	public void setSelf(String self) {
		this.self = self;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/*
	 *
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppCategoryRelationshipsSubcategoriesLinks {\n");
		sb.append("    self: ").append(toIndentedString(this.self)).append("\n");
		sb.append("    related: ").append(toIndentedString(this.related)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
