/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppInfoLocalizationUpdateRequestDataAttributes
 */
@JsonPropertyOrder({ AppInfoLocalizationUpdateRequestDataAttributes.JSON_PROPERTY_NAME,
		AppInfoLocalizationUpdateRequestDataAttributes.JSON_PROPERTY_SUBTITLE,
		AppInfoLocalizationUpdateRequestDataAttributes.JSON_PROPERTY_PRIVACY_POLICY_URL,
		AppInfoLocalizationUpdateRequestDataAttributes.JSON_PROPERTY_PRIVACY_POLICY_TEXT })
public class AppInfoLocalizationUpdateRequestDataAttributes implements Serializable {

	private static final long serialVersionUID = 3696005141551803618L;

	public static final String JSON_PROPERTY_NAME = "name";

	public static final String JSON_PROPERTY_PRIVACY_POLICY_TEXT = "privacyPolicyText";
	public static final String JSON_PROPERTY_PRIVACY_POLICY_URL = "privacyPolicyUrl";

	public static final String JSON_PROPERTY_SUBTITLE = "subtitle";

	private String name;
	private String privacyPolicyText;

	private String privacyPolicyUrl;
	private String subtitle;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppInfoLocalizationUpdateRequestDataAttributes appInfoLocalizationUpdateRequestDataAttributes = (AppInfoLocalizationUpdateRequestDataAttributes) o;
		return Objects.equals(this.name, appInfoLocalizationUpdateRequestDataAttributes.name)
				&& Objects.equals(this.subtitle, appInfoLocalizationUpdateRequestDataAttributes.subtitle)
				&& Objects.equals(this.privacyPolicyUrl,
						appInfoLocalizationUpdateRequestDataAttributes.privacyPolicyUrl)
				&& Objects.equals(this.privacyPolicyText,
						appInfoLocalizationUpdateRequestDataAttributes.privacyPolicyText);
	}

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getName() {
		return this.name;
	}

	@JsonProperty(JSON_PROPERTY_PRIVACY_POLICY_TEXT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getPrivacyPolicyText() {
		return this.privacyPolicyText;
	}

	@JsonProperty(JSON_PROPERTY_PRIVACY_POLICY_URL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getPrivacyPolicyUrl() {
		return this.privacyPolicyUrl;
	}

	@JsonProperty(JSON_PROPERTY_SUBTITLE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getSubtitle() {
		return this.subtitle;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.name, this.subtitle, this.privacyPolicyUrl, this.privacyPolicyText);
	}

	public AppInfoLocalizationUpdateRequestDataAttributes name(String name) {
		this.name = name;
		return this;
	}

	public AppInfoLocalizationUpdateRequestDataAttributes privacyPolicyText(String privacyPolicyText) {
		this.privacyPolicyText = privacyPolicyText;
		return this;
	}

	public AppInfoLocalizationUpdateRequestDataAttributes privacyPolicyUrl(String privacyPolicyUrl) {
		this.privacyPolicyUrl = privacyPolicyUrl;
		return this;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPrivacyPolicyText(String privacyPolicyText) {
		this.privacyPolicyText = privacyPolicyText;
	}

	public void setPrivacyPolicyUrl(String privacyPolicyUrl) {
		this.privacyPolicyUrl = privacyPolicyUrl;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public AppInfoLocalizationUpdateRequestDataAttributes subtitle(String subtitle) {
		this.subtitle = subtitle;
		return this;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppInfoLocalizationUpdateRequestDataAttributes {\n");
		sb.append("    name: ").append(toIndentedString(this.name)).append("\n");
		sb.append("    subtitle: ").append(toIndentedString(this.subtitle)).append("\n");
		sb.append("    privacyPolicyUrl: ").append(toIndentedString(this.privacyPolicyUrl)).append("\n");
		sb.append("    privacyPolicyText: ").append(toIndentedString(this.privacyPolicyText)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
