/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppInfoLocalizationCreateRequestDataAttributes
 */
@JsonPropertyOrder({ AppInfoLocalizationCreateRequestDataAttributes.JSON_PROPERTY_LOCALE,
		AppInfoLocalizationCreateRequestDataAttributes.JSON_PROPERTY_NAME,
		AppInfoLocalizationCreateRequestDataAttributes.JSON_PROPERTY_SUBTITLE,
		AppInfoLocalizationCreateRequestDataAttributes.JSON_PROPERTY_PRIVACY_POLICY_URL,
		AppInfoLocalizationCreateRequestDataAttributes.JSON_PROPERTY_PRIVACY_POLICY_TEXT })
public class AppInfoLocalizationCreateRequestDataAttributes implements Serializable {

	public static final String JSON_PROPERTY_LOCALE = "locale";

	public static final String JSON_PROPERTY_NAME = "name";

	public static final String JSON_PROPERTY_PRIVACY_POLICY_TEXT = "privacyPolicyText";
	public static final String JSON_PROPERTY_PRIVACY_POLICY_URL = "privacyPolicyUrl";

	public static final String JSON_PROPERTY_SUBTITLE = "subtitle";
	private static final long serialVersionUID = -1601292396152899575L;

	private String locale;

	private String name;
	private String privacyPolicyText;

	private String privacyPolicyUrl;
	private String subtitle;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppInfoLocalizationCreateRequestDataAttributes appInfoLocalizationCreateRequestDataAttributes = (AppInfoLocalizationCreateRequestDataAttributes) o;
		return Objects.equals(this.locale, appInfoLocalizationCreateRequestDataAttributes.locale)
				&& Objects.equals(this.name, appInfoLocalizationCreateRequestDataAttributes.name)
				&& Objects.equals(this.subtitle, appInfoLocalizationCreateRequestDataAttributes.subtitle)
				&& Objects.equals(this.privacyPolicyUrl,
						appInfoLocalizationCreateRequestDataAttributes.privacyPolicyUrl)
				&& Objects.equals(this.privacyPolicyText,
						appInfoLocalizationCreateRequestDataAttributes.privacyPolicyText);
	}

	@NotNull
	@JsonProperty(JSON_PROPERTY_LOCALE)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public String getLocale() {
		return this.locale;
	}

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getName() {
		return this.name;
	}

	@JsonProperty(JSON_PROPERTY_PRIVACY_POLICY_TEXT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getPrivacyPolicyText() {
		return this.privacyPolicyText;
	}

	@JsonProperty(JSON_PROPERTY_PRIVACY_POLICY_URL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getPrivacyPolicyUrl() {
		return this.privacyPolicyUrl;
	}

	@JsonProperty(JSON_PROPERTY_SUBTITLE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getSubtitle() {
		return this.subtitle;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.locale, this.name, this.subtitle, this.privacyPolicyUrl, this.privacyPolicyText);
	}

	public AppInfoLocalizationCreateRequestDataAttributes locale(String locale) {
		this.locale = locale;
		return this;
	}

	public AppInfoLocalizationCreateRequestDataAttributes name(String name) {
		this.name = name;
		return this;
	}

	public AppInfoLocalizationCreateRequestDataAttributes privacyPolicyText(String privacyPolicyText) {
		this.privacyPolicyText = privacyPolicyText;
		return this;
	}

	public AppInfoLocalizationCreateRequestDataAttributes privacyPolicyUrl(String privacyPolicyUrl) {
		this.privacyPolicyUrl = privacyPolicyUrl;
		return this;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPrivacyPolicyText(String privacyPolicyText) {
		this.privacyPolicyText = privacyPolicyText;
	}

	public void setPrivacyPolicyUrl(String privacyPolicyUrl) {
		this.privacyPolicyUrl = privacyPolicyUrl;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public AppInfoLocalizationCreateRequestDataAttributes subtitle(String subtitle) {
		this.subtitle = subtitle;
		return this;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppInfoLocalizationCreateRequestDataAttributes {\n");
		sb.append("    locale: ").append(toIndentedString(this.locale)).append("\n");
		sb.append("    name: ").append(toIndentedString(this.name)).append("\n");
		sb.append("    subtitle: ").append(toIndentedString(this.subtitle)).append("\n");
		sb.append("    privacyPolicyUrl: ").append(toIndentedString(this.privacyPolicyUrl)).append("\n");
		sb.append("    privacyPolicyText: ").append(toIndentedString(this.privacyPolicyText)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
