/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AppMediaAssetState
 */
@JsonPropertyOrder({ AppMediaAssetState.JSON_PROPERTY_ERRORS, AppMediaAssetState.JSON_PROPERTY_WARNINGS,
		AppMediaAssetState.JSON_PROPERTY_STATE })
public class AppMediaAssetState implements Serializable {

	/**
	 * Gets or Sets state
	 */
	public enum StateEnum {
		AWAITING_UPLOAD("AWAITING_UPLOAD"),

		COMPLETE("COMPLETE"),

		FAILED("FAILED"),

		UPLOAD_COMPLETE("UPLOAD_COMPLETE");

		@JsonCreator
		public static StateEnum fromValue(String value) {
			for (StateEnum b : StateEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			throw new IllegalArgumentException("Unexpected value '" + value + "'");
		}

		private String value;

		StateEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return this.value;
		}

		@Override
		public String toString() {
			return String.valueOf(this.value);
		}
	}

	public static final String JSON_PROPERTY_ERRORS = "errors";

	public static final String JSON_PROPERTY_STATE = "state";
	public static final String JSON_PROPERTY_WARNINGS = "warnings";

	private static final long serialVersionUID = -6728271854538693027L;

	private List<AppMediaStateError> errors = null;

	private StateEnum state;
	private List<AppMediaStateError> warnings = null;

	public AppMediaAssetState addErrorsItem(AppMediaStateError errorsItem) {
		if (this.errors == null) {
			this.errors = new ArrayList<>();
		}
		this.errors.add(errorsItem);
		return this;
	}

	public AppMediaAssetState addWarningsItem(AppMediaStateError warningsItem) {
		if (this.warnings == null) {
			this.warnings = new ArrayList<>();
		}
		this.warnings.add(warningsItem);
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppMediaAssetState appMediaAssetState = (AppMediaAssetState) o;
		return Objects.equals(this.errors, appMediaAssetState.errors)
				&& Objects.equals(this.warnings, appMediaAssetState.warnings)
				&& Objects.equals(this.state, appMediaAssetState.state);
	}

	public AppMediaAssetState errors(List<AppMediaStateError> errors) {
		this.errors = errors;
		return this;
	}

	@Valid
	@JsonProperty(JSON_PROPERTY_ERRORS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public List<AppMediaStateError> getErrors() {
		return this.errors;
	}

	@JsonProperty(JSON_PROPERTY_STATE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public StateEnum getState() {
		return this.state;
	}

	@Valid
	@JsonProperty(JSON_PROPERTY_WARNINGS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public List<AppMediaStateError> getWarnings() {
		return this.warnings;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.errors, this.warnings, this.state);
	}

	public void setErrors(List<AppMediaStateError> errors) {
		this.errors = errors;
	}

	public void setState(StateEnum state) {
		this.state = state;
	}

	public void setWarnings(List<AppMediaStateError> warnings) {
		this.warnings = warnings;
	}

	public AppMediaAssetState state(StateEnum state) {
		this.state = state;
		return this;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppMediaAssetState {\n");
		sb.append("    errors: ").append(toIndentedString(this.errors)).append("\n");
		sb.append("    warnings: ").append(toIndentedString(this.warnings)).append("\n");
		sb.append("    state: ").append(toIndentedString(this.state)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	public AppMediaAssetState warnings(List<AppMediaStateError> warnings) {
		this.warnings = warnings;
		return this;
	}

}
