/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppPreviewRelationships
 */
@JsonPropertyOrder({ AppPreviewRelationships.JSON_PROPERTY_APP_PREVIEW_SET })
public class AppPreviewRelationships implements Serializable {

	private static final long serialVersionUID = 2727247745257329042L;

	public static final String JSON_PROPERTY_APP_PREVIEW_SET = "appPreviewSet";

	private AppPreviewRelationshipsAppPreviewSet appPreviewSet;

	public AppPreviewRelationships appPreviewSet(AppPreviewRelationshipsAppPreviewSet appPreviewSet) {
		this.appPreviewSet = appPreviewSet;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppPreviewRelationships appPreviewRelationships = (AppPreviewRelationships) o;
		return Objects.equals(this.appPreviewSet, appPreviewRelationships.appPreviewSet);
	}

	@Valid
	@JsonProperty(JSON_PROPERTY_APP_PREVIEW_SET)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public AppPreviewRelationshipsAppPreviewSet getAppPreviewSet() {
		return this.appPreviewSet;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.appPreviewSet);
	}

	public void setAppPreviewSet(AppPreviewRelationshipsAppPreviewSet appPreviewSet) {
		this.appPreviewSet = appPreviewSet;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppPreviewRelationships {\n");
		sb.append("    appPreviewSet: ").append(toIndentedString(this.appPreviewSet)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
