/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppPricePointAttributes
 */
@JsonPropertyOrder({ AppPricePointAttributes.JSON_PROPERTY_CUSTOMER_PRICE,
		AppPricePointAttributes.JSON_PROPERTY_PROCEEDS })
public class AppPricePointAttributes implements Serializable {

	public static final String JSON_PROPERTY_CUSTOMER_PRICE = "customerPrice";

	public static final String JSON_PROPERTY_PROCEEDS = "proceeds";

	private static final long serialVersionUID = -1582188535462690584L;

	private String customerPrice;
	private String proceeds;

	public AppPricePointAttributes customerPrice(String customerPrice) {

		this.customerPrice = customerPrice;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppPricePointAttributes appPricePointAttributes = (AppPricePointAttributes) o;
		return Objects.equals(this.customerPrice, appPricePointAttributes.customerPrice)
				&& Objects.equals(this.proceeds, appPricePointAttributes.proceeds);
	}

	@JsonProperty(JSON_PROPERTY_CUSTOMER_PRICE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getCustomerPrice() {
		return this.customerPrice;
	}

	@JsonProperty(JSON_PROPERTY_PROCEEDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getProceeds() {
		return this.proceeds;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.customerPrice, this.proceeds);
	}

	public AppPricePointAttributes proceeds(String proceeds) {
		this.proceeds = proceeds;
		return this;
	}

	public void setCustomerPrice(String customerPrice) {
		this.customerPrice = customerPrice;
	}

	public void setProceeds(String proceeds) {
		this.proceeds = proceeds;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppPricePointAttributes {\n");
		sb.append("    customerPrice: ").append(toIndentedString(this.customerPrice)).append("\n");
		sb.append("    proceeds: ").append(toIndentedString(this.proceeds)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
