/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppPreviewCreateRequestDataAttributes
 */
@JsonPropertyOrder({ AppPreviewCreateRequestDataAttributes.JSON_PROPERTY_FILE_SIZE,
		AppPreviewCreateRequestDataAttributes.JSON_PROPERTY_FILE_NAME,
		AppPreviewCreateRequestDataAttributes.JSON_PROPERTY_PREVIEW_FRAME_TIME_CODE,
		AppPreviewCreateRequestDataAttributes.JSON_PROPERTY_MIME_TYPE })
public class AppPreviewCreateRequestDataAttributes implements Serializable {

	private static final long serialVersionUID = 5180455094027238401L;

	public static final String JSON_PROPERTY_FILE_NAME = "fileName";

	public static final String JSON_PROPERTY_FILE_SIZE = "fileSize";
	public static final String JSON_PROPERTY_MIME_TYPE = "mimeType";

	public static final String JSON_PROPERTY_PREVIEW_FRAME_TIME_CODE = "previewFrameTimeCode";

	private String fileName;
	private Integer fileSize;

	private String mimeType;
	private String previewFrameTimeCode;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppPreviewCreateRequestDataAttributes appPreviewCreateRequestDataAttributes = (AppPreviewCreateRequestDataAttributes) o;
		return Objects.equals(this.fileSize, appPreviewCreateRequestDataAttributes.fileSize)
				&& Objects.equals(this.fileName, appPreviewCreateRequestDataAttributes.fileName)
				&& Objects.equals(this.previewFrameTimeCode, appPreviewCreateRequestDataAttributes.previewFrameTimeCode)
				&& Objects.equals(this.mimeType, appPreviewCreateRequestDataAttributes.mimeType);
	}

	public AppPreviewCreateRequestDataAttributes fileName(String fileName) {
		this.fileName = fileName;
		return this;
	}

	public AppPreviewCreateRequestDataAttributes fileSize(Integer fileSize) {

		this.fileSize = fileSize;
		return this;
	}

	@NotNull
	@JsonProperty(JSON_PROPERTY_FILE_NAME)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public String getFileName() {
		return this.fileName;
	}

	@NotNull
	@JsonProperty(JSON_PROPERTY_FILE_SIZE)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public Integer getFileSize() {
		return this.fileSize;
	}

	@JsonProperty(JSON_PROPERTY_MIME_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getMimeType() {
		return this.mimeType;
	}

	@JsonProperty(JSON_PROPERTY_PREVIEW_FRAME_TIME_CODE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public String getPreviewFrameTimeCode() {
		return this.previewFrameTimeCode;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.fileSize, this.fileName, this.previewFrameTimeCode, this.mimeType);
	}

	public AppPreviewCreateRequestDataAttributes mimeType(String mimeType) {
		this.mimeType = mimeType;
		return this;
	}

	public AppPreviewCreateRequestDataAttributes previewFrameTimeCode(String previewFrameTimeCode) {
		this.previewFrameTimeCode = previewFrameTimeCode;
		return this;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public void setPreviewFrameTimeCode(String previewFrameTimeCode) {
		this.previewFrameTimeCode = previewFrameTimeCode;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppPreviewCreateRequestDataAttributes {\n");
		sb.append("    fileSize: ").append(toIndentedString(this.fileSize)).append("\n");
		sb.append("    fileName: ").append(toIndentedString(this.fileName)).append("\n");
		sb.append("    previewFrameTimeCode: ").append(toIndentedString(this.previewFrameTimeCode)).append("\n");
		sb.append("    mimeType: ").append(toIndentedString(this.mimeType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
