/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AppStoreVersionUpdateRequestDataAttributes
 */
@JsonPropertyOrder({ AppStoreVersionUpdateRequestDataAttributes.JSON_PROPERTY_VERSION_STRING,
		AppStoreVersionUpdateRequestDataAttributes.JSON_PROPERTY_COPYRIGHT,
		AppStoreVersionUpdateRequestDataAttributes.JSON_PROPERTY_RELEASE_TYPE,
		AppStoreVersionUpdateRequestDataAttributes.JSON_PROPERTY_EARLIEST_RELEASE_DATE,
		AppStoreVersionUpdateRequestDataAttributes.JSON_PROPERTY_USES_IDFA,
		AppStoreVersionUpdateRequestDataAttributes.JSON_PROPERTY_DOWNLOADABLE })

public class AppStoreVersionUpdateRequestDataAttributes implements Serializable {
	/**
	 * Gets or Sets releaseType
	 */
	public enum ReleaseTypeEnum {
		AFTER_APPROVAL("AFTER_APPROVAL"),

		MANUAL("MANUAL"),

		SCHEDULED("SCHEDULED");

		@JsonCreator
		public static ReleaseTypeEnum fromValue(String value) {
			for (ReleaseTypeEnum b : ReleaseTypeEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			throw new IllegalArgumentException("Unexpected value '" + value + "'");
		}

		private String value;

		ReleaseTypeEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return this.value;
		}

		@Override
		public String toString() {
			return String.valueOf(this.value);
		}
	}

	public static final String JSON_PROPERTY_COPYRIGHT = "copyright";

	public static final String JSON_PROPERTY_DOWNLOADABLE = "downloadable";
	public static final String JSON_PROPERTY_EARLIEST_RELEASE_DATE = "earliestReleaseDate";

	public static final String JSON_PROPERTY_RELEASE_TYPE = "releaseType";
	public static final String JSON_PROPERTY_USES_IDFA = "usesIdfa";

	public static final String JSON_PROPERTY_VERSION_STRING = "versionString";

	/**
	 *
	 */
	private static final long serialVersionUID = -4314729602090302156L;

	private String copyright;
	private Boolean downloadable;

	private OffsetDateTime earliestReleaseDate;
	private ReleaseTypeEnum releaseType;

	private Boolean usesIdfa;
	private String versionString;

	public AppStoreVersionUpdateRequestDataAttributes copyright(String copyright) {

		this.copyright = copyright;
		return this;
	}

	public AppStoreVersionUpdateRequestDataAttributes downloadable(Boolean downloadable) {

		this.downloadable = downloadable;
		return this;
	}

	public AppStoreVersionUpdateRequestDataAttributes earliestReleaseDate(OffsetDateTime earliestReleaseDate) {

		this.earliestReleaseDate = earliestReleaseDate;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppStoreVersionUpdateRequestDataAttributes appStoreVersionUpdateRequestDataAttributes = (AppStoreVersionUpdateRequestDataAttributes) o;
		return Objects.equals(this.versionString, appStoreVersionUpdateRequestDataAttributes.versionString)
				&& Objects.equals(this.copyright, appStoreVersionUpdateRequestDataAttributes.copyright)
				&& Objects.equals(this.releaseType, appStoreVersionUpdateRequestDataAttributes.releaseType)
				&& Objects.equals(this.earliestReleaseDate,
						appStoreVersionUpdateRequestDataAttributes.earliestReleaseDate)
				&& Objects.equals(this.usesIdfa, appStoreVersionUpdateRequestDataAttributes.usesIdfa)
				&& Objects.equals(this.downloadable, appStoreVersionUpdateRequestDataAttributes.downloadable);
	}

	/**
	 * Get copyright
	 *
	 * @return copyright
	 **/

	@JsonProperty(JSON_PROPERTY_COPYRIGHT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getCopyright() {
		return this.copyright;
	}

	/**
	 * Get downloadable
	 *
	 * @return downloadable
	 **/

	@JsonProperty(JSON_PROPERTY_DOWNLOADABLE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getDownloadable() {
		return this.downloadable;
	}

	/**
	 * Get earliestReleaseDate
	 *
	 * @return earliestReleaseDate
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_EARLIEST_RELEASE_DATE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public OffsetDateTime getEarliestReleaseDate() {
		return this.earliestReleaseDate;
	}

	/**
	 * Get releaseType
	 *
	 * @return releaseType
	 **/

	@JsonProperty(JSON_PROPERTY_RELEASE_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public ReleaseTypeEnum getReleaseType() {
		return this.releaseType;
	}

	/**
	 * Get usesIdfa
	 *
	 * @return usesIdfa
	 **/

	@JsonProperty(JSON_PROPERTY_USES_IDFA)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getUsesIdfa() {
		return this.usesIdfa;
	}

	/**
	 * Get versionString
	 *
	 * @return versionString
	 **/

	@JsonProperty(JSON_PROPERTY_VERSION_STRING)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getVersionString() {
		return this.versionString;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.versionString, this.copyright, this.releaseType, this.earliestReleaseDate,
				this.usesIdfa, this.downloadable);
	}

	public AppStoreVersionUpdateRequestDataAttributes releaseType(ReleaseTypeEnum releaseType) {

		this.releaseType = releaseType;
		return this;
	}

	public void setCopyright(String copyright) {
		this.copyright = copyright;
	}

	public void setDownloadable(Boolean downloadable) {
		this.downloadable = downloadable;
	}

	public void setEarliestReleaseDate(OffsetDateTime earliestReleaseDate) {
		this.earliestReleaseDate = earliestReleaseDate;
	}

	public void setReleaseType(ReleaseTypeEnum releaseType) {
		this.releaseType = releaseType;
	}

	public void setUsesIdfa(Boolean usesIdfa) {
		this.usesIdfa = usesIdfa;
	}

	public void setVersionString(String versionString) {
		this.versionString = versionString;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppStoreVersionUpdateRequestDataAttributes {\n");
		sb.append("    versionString: ").append(toIndentedString(this.versionString)).append("\n");
		sb.append("    copyright: ").append(toIndentedString(this.copyright)).append("\n");
		sb.append("    releaseType: ").append(toIndentedString(this.releaseType)).append("\n");
		sb.append("    earliestReleaseDate: ").append(toIndentedString(this.earliestReleaseDate)).append("\n");
		sb.append("    usesIdfa: ").append(toIndentedString(this.usesIdfa)).append("\n");
		sb.append("    downloadable: ").append(toIndentedString(this.downloadable)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	public AppStoreVersionUpdateRequestDataAttributes usesIdfa(Boolean usesIdfa) {

		this.usesIdfa = usesIdfa;
		return this;
	}

	public AppStoreVersionUpdateRequestDataAttributes versionString(String versionString) {

		this.versionString = versionString;
		return this;
	}

}
