/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppStoreReviewDetailAttributes
 */
@JsonPropertyOrder({ AppStoreReviewDetailAttributes.JSON_PROPERTY_CONTACT_FIRST_NAME,
		AppStoreReviewDetailAttributes.JSON_PROPERTY_CONTACT_LAST_NAME,
		AppStoreReviewDetailAttributes.JSON_PROPERTY_CONTACT_PHONE,
		AppStoreReviewDetailAttributes.JSON_PROPERTY_CONTACT_EMAIL,
		AppStoreReviewDetailAttributes.JSON_PROPERTY_DEMO_ACCOUNT_NAME,
		AppStoreReviewDetailAttributes.JSON_PROPERTY_DEMO_ACCOUNT_PASSWORD,
		AppStoreReviewDetailAttributes.JSON_PROPERTY_DEMO_ACCOUNT_REQUIRED,
		AppStoreReviewDetailAttributes.JSON_PROPERTY_NOTES })

public class AppStoreReviewDetailAttributes implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -5406133898554423006L;

	public static final String JSON_PROPERTY_CONTACT_EMAIL = "contactEmail";

	public static final String JSON_PROPERTY_CONTACT_FIRST_NAME = "contactFirstName";
	public static final String JSON_PROPERTY_CONTACT_LAST_NAME = "contactLastName";

	public static final String JSON_PROPERTY_CONTACT_PHONE = "contactPhone";
	public static final String JSON_PROPERTY_DEMO_ACCOUNT_NAME = "demoAccountName";

	public static final String JSON_PROPERTY_DEMO_ACCOUNT_PASSWORD = "demoAccountPassword";
	public static final String JSON_PROPERTY_DEMO_ACCOUNT_REQUIRED = "demoAccountRequired";

	public static final String JSON_PROPERTY_NOTES = "notes";

	private String contactEmail;
	private String contactFirstName;

	private String contactLastName;
	private String contactPhone;

	private String demoAccountName;
	private String demoAccountPassword;

	private Boolean demoAccountRequired;
	private String notes;

	public AppStoreReviewDetailAttributes contactEmail(String contactEmail) {

		this.contactEmail = contactEmail;
		return this;
	}

	public AppStoreReviewDetailAttributes contactFirstName(String contactFirstName) {

		this.contactFirstName = contactFirstName;
		return this;
	}

	public AppStoreReviewDetailAttributes contactLastName(String contactLastName) {

		this.contactLastName = contactLastName;
		return this;
	}

	public AppStoreReviewDetailAttributes contactPhone(String contactPhone) {

		this.contactPhone = contactPhone;
		return this;
	}

	public AppStoreReviewDetailAttributes demoAccountName(String demoAccountName) {

		this.demoAccountName = demoAccountName;
		return this;
	}

	public AppStoreReviewDetailAttributes demoAccountPassword(String demoAccountPassword) {

		this.demoAccountPassword = demoAccountPassword;
		return this;
	}

	public AppStoreReviewDetailAttributes demoAccountRequired(Boolean demoAccountRequired) {

		this.demoAccountRequired = demoAccountRequired;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppStoreReviewDetailAttributes appStoreReviewDetailAttributes = (AppStoreReviewDetailAttributes) o;
		return Objects.equals(this.contactFirstName, appStoreReviewDetailAttributes.contactFirstName)
				&& Objects.equals(this.contactLastName, appStoreReviewDetailAttributes.contactLastName)
				&& Objects.equals(this.contactPhone, appStoreReviewDetailAttributes.contactPhone)
				&& Objects.equals(this.contactEmail, appStoreReviewDetailAttributes.contactEmail)
				&& Objects.equals(this.demoAccountName, appStoreReviewDetailAttributes.demoAccountName)
				&& Objects.equals(this.demoAccountPassword, appStoreReviewDetailAttributes.demoAccountPassword)
				&& Objects.equals(this.demoAccountRequired, appStoreReviewDetailAttributes.demoAccountRequired)
				&& Objects.equals(this.notes, appStoreReviewDetailAttributes.notes);
	}

	/**
	 * Get contactEmail
	 *
	 * @return contactEmail
	 **/

	@JsonProperty(JSON_PROPERTY_CONTACT_EMAIL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getContactEmail() {
		return this.contactEmail;
	}

	/**
	 * Get contactFirstName
	 *
	 * @return contactFirstName
	 **/

	@JsonProperty(JSON_PROPERTY_CONTACT_FIRST_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getContactFirstName() {
		return this.contactFirstName;
	}

	/**
	 * Get contactLastName
	 *
	 * @return contactLastName
	 **/

	@JsonProperty(JSON_PROPERTY_CONTACT_LAST_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getContactLastName() {
		return this.contactLastName;
	}

	/**
	 * Get contactPhone
	 *
	 * @return contactPhone
	 **/

	@JsonProperty(JSON_PROPERTY_CONTACT_PHONE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getContactPhone() {
		return this.contactPhone;
	}

	/**
	 * Get demoAccountName
	 *
	 * @return demoAccountName
	 **/

	@JsonProperty(JSON_PROPERTY_DEMO_ACCOUNT_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getDemoAccountName() {
		return this.demoAccountName;
	}

	/**
	 * Get demoAccountPassword
	 *
	 * @return demoAccountPassword
	 **/

	@JsonProperty(JSON_PROPERTY_DEMO_ACCOUNT_PASSWORD)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getDemoAccountPassword() {
		return this.demoAccountPassword;
	}

	/**
	 * Get demoAccountRequired
	 *
	 * @return demoAccountRequired
	 **/

	@JsonProperty(JSON_PROPERTY_DEMO_ACCOUNT_REQUIRED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getDemoAccountRequired() {
		return this.demoAccountRequired;
	}

	/**
	 * Get notes
	 *
	 * @return notes
	 **/

	@JsonProperty(JSON_PROPERTY_NOTES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getNotes() {
		return this.notes;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.contactFirstName, this.contactLastName, this.contactPhone, this.contactEmail,
				this.demoAccountName, this.demoAccountPassword, this.demoAccountRequired, this.notes);
	}

	public AppStoreReviewDetailAttributes notes(String notes) {

		this.notes = notes;
		return this;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public void setContactFirstName(String contactFirstName) {
		this.contactFirstName = contactFirstName;
	}

	public void setContactLastName(String contactLastName) {
		this.contactLastName = contactLastName;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public void setDemoAccountName(String demoAccountName) {
		this.demoAccountName = demoAccountName;
	}

	public void setDemoAccountPassword(String demoAccountPassword) {
		this.demoAccountPassword = demoAccountPassword;
	}

	public void setDemoAccountRequired(Boolean demoAccountRequired) {
		this.demoAccountRequired = demoAccountRequired;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppStoreReviewDetailAttributes {\n");
		sb.append("    contactFirstName: ").append(toIndentedString(this.contactFirstName)).append("\n");
		sb.append("    contactLastName: ").append(toIndentedString(this.contactLastName)).append("\n");
		sb.append("    contactPhone: ").append(toIndentedString(this.contactPhone)).append("\n");
		sb.append("    contactEmail: ").append(toIndentedString(this.contactEmail)).append("\n");
		sb.append("    demoAccountName: ").append(toIndentedString(this.demoAccountName)).append("\n");
		sb.append("    demoAccountPassword: ").append(toIndentedString(this.demoAccountPassword)).append("\n");
		sb.append("    demoAccountRequired: ").append(toIndentedString(this.demoAccountRequired)).append("\n");
		sb.append("    notes: ").append(toIndentedString(this.notes)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
