/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppScreenshotSetAttributes
 */
@JsonPropertyOrder({ AppScreenshotSetAttributes.JSON_PROPERTY_SCREENSHOT_DISPLAY_TYPE })
public class AppScreenshotSetAttributes implements Serializable {

	public static final String JSON_PROPERTY_SCREENSHOT_DISPLAY_TYPE = "screenshotDisplayType";

	private static final long serialVersionUID = 3570745832229549456L;

	private ScreenshotDisplayType screenshotDisplayType;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppScreenshotSetAttributes appScreenshotSetAttributes = (AppScreenshotSetAttributes) o;
		return Objects.equals(this.screenshotDisplayType, appScreenshotSetAttributes.screenshotDisplayType);
	}

	@Valid
	@JsonProperty(JSON_PROPERTY_SCREENSHOT_DISPLAY_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public ScreenshotDisplayType getScreenshotDisplayType() {
		return this.screenshotDisplayType;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.screenshotDisplayType);
	}

	public AppScreenshotSetAttributes screenshotDisplayType(ScreenshotDisplayType screenshotDisplayType) {
		this.screenshotDisplayType = screenshotDisplayType;
		return this;
	}

	public void setScreenshotDisplayType(ScreenshotDisplayType screenshotDisplayType) {
		this.screenshotDisplayType = screenshotDisplayType;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppScreenshotSetAttributes {\n");
		sb.append("    screenshotDisplayType: ").append(toIndentedString(this.screenshotDisplayType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
