/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.net.URI;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppStoreVersionLocalizationAttributes
 */
@JsonPropertyOrder({ AppStoreVersionLocalizationAttributes.JSON_PROPERTY_DESCRIPTION,
		AppStoreVersionLocalizationAttributes.JSON_PROPERTY_LOCALE,
		AppStoreVersionLocalizationAttributes.JSON_PROPERTY_KEYWORDS,
		AppStoreVersionLocalizationAttributes.JSON_PROPERTY_MARKETING_URL,
		AppStoreVersionLocalizationAttributes.JSON_PROPERTY_PROMOTIONAL_TEXT,
		AppStoreVersionLocalizationAttributes.JSON_PROPERTY_SUPPORT_URL,
		AppStoreVersionLocalizationAttributes.JSON_PROPERTY_WHATS_NEW })

public class AppStoreVersionLocalizationAttributes implements Serializable {
	public static final String JSON_PROPERTY_DESCRIPTION = "description";

	public static final String JSON_PROPERTY_KEYWORDS = "keywords";

	public static final String JSON_PROPERTY_LOCALE = "locale";
	public static final String JSON_PROPERTY_MARKETING_URL = "marketingUrl";

	public static final String JSON_PROPERTY_PROMOTIONAL_TEXT = "promotionalText";
	public static final String JSON_PROPERTY_SUPPORT_URL = "supportUrl";

	public static final String JSON_PROPERTY_WHATS_NEW = "whatsNew";
	/**
	 *
	 */
	private static final long serialVersionUID = -5851875829437763175L;

	private String description;

	private String keywords;
	private String locale;

	private URI marketingUrl;
	private String promotionalText;

	private URI supportUrl;
	private String whatsNew;

	public AppStoreVersionLocalizationAttributes description(String description) {

		this.description = description;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppStoreVersionLocalizationAttributes appStoreVersionLocalizationAttributes = (AppStoreVersionLocalizationAttributes) o;
		return Objects.equals(this.description, appStoreVersionLocalizationAttributes.description)
				&& Objects.equals(this.locale, appStoreVersionLocalizationAttributes.locale)
				&& Objects.equals(this.keywords, appStoreVersionLocalizationAttributes.keywords)
				&& Objects.equals(this.marketingUrl, appStoreVersionLocalizationAttributes.marketingUrl)
				&& Objects.equals(this.promotionalText, appStoreVersionLocalizationAttributes.promotionalText)
				&& Objects.equals(this.supportUrl, appStoreVersionLocalizationAttributes.supportUrl)
				&& Objects.equals(this.whatsNew, appStoreVersionLocalizationAttributes.whatsNew);
	}

	/**
	 * Get description
	 *
	 * @return description
	 **/

	@JsonProperty(JSON_PROPERTY_DESCRIPTION)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getDescription() {
		return this.description;
	}

	/**
	 * Get keywords
	 *
	 * @return keywords
	 **/

	@JsonProperty(JSON_PROPERTY_KEYWORDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getKeywords() {
		return this.keywords;
	}

	/**
	 * Get locale
	 *
	 * @return locale
	 **/

	@JsonProperty(JSON_PROPERTY_LOCALE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getLocale() {
		return this.locale;
	}

	/**
	 * Get marketingUrl
	 *
	 * @return marketingUrl
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_MARKETING_URL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public URI getMarketingUrl() {
		return this.marketingUrl;
	}

	/**
	 * Get promotionalText
	 *
	 * @return promotionalText
	 **/

	@JsonProperty(JSON_PROPERTY_PROMOTIONAL_TEXT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getPromotionalText() {
		return this.promotionalText;
	}

	/**
	 * Get supportUrl
	 *
	 * @return supportUrl
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_SUPPORT_URL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public URI getSupportUrl() {
		return this.supportUrl;
	}

	/**
	 * Get whatsNew
	 *
	 * @return whatsNew
	 **/

	@JsonProperty(JSON_PROPERTY_WHATS_NEW)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getWhatsNew() {
		return this.whatsNew;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.description, this.locale, this.keywords, this.marketingUrl, this.promotionalText,
				this.supportUrl, this.whatsNew);
	}

	public AppStoreVersionLocalizationAttributes keywords(String keywords) {

		this.keywords = keywords;
		return this;
	}

	public AppStoreVersionLocalizationAttributes locale(String locale) {

		this.locale = locale;
		return this;
	}

	public AppStoreVersionLocalizationAttributes marketingUrl(URI marketingUrl) {

		this.marketingUrl = marketingUrl;
		return this;
	}

	public AppStoreVersionLocalizationAttributes promotionalText(String promotionalText) {

		this.promotionalText = promotionalText;
		return this;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public void setMarketingUrl(URI marketingUrl) {
		this.marketingUrl = marketingUrl;
	}

	public void setPromotionalText(String promotionalText) {
		this.promotionalText = promotionalText;
	}

	public void setSupportUrl(URI supportUrl) {
		this.supportUrl = supportUrl;
	}

	public void setWhatsNew(String whatsNew) {
		this.whatsNew = whatsNew;
	}

	public AppStoreVersionLocalizationAttributes supportUrl(URI supportUrl) {

		this.supportUrl = supportUrl;
		return this;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppStoreVersionLocalizationAttributes {\n");
		sb.append("    description: ").append(toIndentedString(this.description)).append("\n");
		sb.append("    locale: ").append(toIndentedString(this.locale)).append("\n");
		sb.append("    keywords: ").append(toIndentedString(this.keywords)).append("\n");
		sb.append("    marketingUrl: ").append(toIndentedString(this.marketingUrl)).append("\n");
		sb.append("    promotionalText: ").append(toIndentedString(this.promotionalText)).append("\n");
		sb.append("    supportUrl: ").append(toIndentedString(this.supportUrl)).append("\n");
		sb.append("    whatsNew: ").append(toIndentedString(this.whatsNew)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	public AppStoreVersionLocalizationAttributes whatsNew(String whatsNew) {

		this.whatsNew = whatsNew;
		return this;
	}

}
