/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppStoreReviewDetailRelationships
 */
@JsonPropertyOrder({ AppStoreReviewDetailRelationships.JSON_PROPERTY_APP_STORE_VERSION,
		AppStoreReviewDetailRelationships.JSON_PROPERTY_APP_STORE_REVIEW_ATTACHMENTS })

public class AppStoreReviewDetailRelationships implements Serializable {
	public static final String JSON_PROPERTY_APP_STORE_REVIEW_ATTACHMENTS = "appStoreReviewAttachments";

	public static final String JSON_PROPERTY_APP_STORE_VERSION = "appStoreVersion";

	/**
	 *
	 */
	private static final long serialVersionUID = -1606952779106993089L;

	private AppStoreReviewDetailRelationshipsAppStoreReviewAttachments appStoreReviewAttachments;
	private AppStoreReviewDetailRelationshipsAppStoreVersion appStoreVersion;

	public AppStoreReviewDetailRelationships appStoreReviewAttachments(
			AppStoreReviewDetailRelationshipsAppStoreReviewAttachments appStoreReviewAttachments) {

		this.appStoreReviewAttachments = appStoreReviewAttachments;
		return this;
	}

	public AppStoreReviewDetailRelationships appStoreVersion(
			AppStoreReviewDetailRelationshipsAppStoreVersion appStoreVersion) {

		this.appStoreVersion = appStoreVersion;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppStoreReviewDetailRelationships appStoreReviewDetailRelationships = (AppStoreReviewDetailRelationships) o;
		return Objects.equals(this.appStoreVersion, appStoreReviewDetailRelationships.appStoreVersion) && Objects
				.equals(this.appStoreReviewAttachments, appStoreReviewDetailRelationships.appStoreReviewAttachments);
	}

	/**
	 * Get appStoreReviewAttachments
	 *
	 * @return appStoreReviewAttachments
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_APP_STORE_REVIEW_ATTACHMENTS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppStoreReviewDetailRelationshipsAppStoreReviewAttachments getAppStoreReviewAttachments() {
		return this.appStoreReviewAttachments;
	}

	/**
	 * Get appStoreVersion
	 *
	 * @return appStoreVersion
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_APP_STORE_VERSION)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppStoreReviewDetailRelationshipsAppStoreVersion getAppStoreVersion() {
		return this.appStoreVersion;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.appStoreVersion, this.appStoreReviewAttachments);
	}

	public void setAppStoreReviewAttachments(
			AppStoreReviewDetailRelationshipsAppStoreReviewAttachments appStoreReviewAttachments) {
		this.appStoreReviewAttachments = appStoreReviewAttachments;
	}

	public void setAppStoreVersion(AppStoreReviewDetailRelationshipsAppStoreVersion appStoreVersion) {
		this.appStoreVersion = appStoreVersion;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppStoreReviewDetailRelationships {\n");
		sb.append("    appStoreVersion: ").append(toIndentedString(this.appStoreVersion)).append("\n");
		sb.append("    appStoreReviewAttachments: ").append(toIndentedString(this.appStoreReviewAttachments))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

}
