/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppStoreReviewAttachmentAttributes
 */
@JsonPropertyOrder({ AppStoreReviewAttachmentAttributes.JSON_PROPERTY_FILE_SIZE,
		AppStoreReviewAttachmentAttributes.JSON_PROPERTY_FILE_NAME,
		AppStoreReviewAttachmentAttributes.JSON_PROPERTY_SOURCE_FILE_CHECKSUM,
		AppStoreReviewAttachmentAttributes.JSON_PROPERTY_UPLOAD_OPERATIONS,
		AppStoreReviewAttachmentAttributes.JSON_PROPERTY_ASSET_DELIVERY_STATE })

public class AppStoreReviewAttachmentAttributes implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -309973818771062204L;

	public static final String JSON_PROPERTY_ASSET_DELIVERY_STATE = "assetDeliveryState";

	public static final String JSON_PROPERTY_FILE_NAME = "fileName";
	public static final String JSON_PROPERTY_FILE_SIZE = "fileSize";

	public static final String JSON_PROPERTY_SOURCE_FILE_CHECKSUM = "sourceFileChecksum";
	public static final String JSON_PROPERTY_UPLOAD_OPERATIONS = "uploadOperations";

	private AppMediaAssetState assetDeliveryState;

	private String fileName;
	private Integer fileSize;

	private String sourceFileChecksum;
	private List<UploadOperation> uploadOperations = null;

	public AppStoreReviewAttachmentAttributes addUploadOperationsItem(UploadOperation uploadOperationsItem) {
		if (this.uploadOperations == null) {
			this.uploadOperations = new ArrayList<>();
		}
		this.uploadOperations.add(uploadOperationsItem);
		return this;
	}

	public AppStoreReviewAttachmentAttributes assetDeliveryState(AppMediaAssetState assetDeliveryState) {

		this.assetDeliveryState = assetDeliveryState;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppStoreReviewAttachmentAttributes appStoreReviewAttachmentAttributes = (AppStoreReviewAttachmentAttributes) o;
		return Objects.equals(this.fileSize, appStoreReviewAttachmentAttributes.fileSize)
				&& Objects.equals(this.fileName, appStoreReviewAttachmentAttributes.fileName)
				&& Objects.equals(this.sourceFileChecksum, appStoreReviewAttachmentAttributes.sourceFileChecksum)
				&& Objects.equals(this.uploadOperations, appStoreReviewAttachmentAttributes.uploadOperations)
				&& Objects.equals(this.assetDeliveryState, appStoreReviewAttachmentAttributes.assetDeliveryState);
	}

	public AppStoreReviewAttachmentAttributes fileName(String fileName) {

		this.fileName = fileName;
		return this;
	}

	public AppStoreReviewAttachmentAttributes fileSize(Integer fileSize) {

		this.fileSize = fileSize;
		return this;
	}

	/**
	 * Get assetDeliveryState
	 *
	 * @return assetDeliveryState
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_ASSET_DELIVERY_STATE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppMediaAssetState getAssetDeliveryState() {
		return this.assetDeliveryState;
	}

	/**
	 * Get fileName
	 *
	 * @return fileName
	 **/

	@JsonProperty(JSON_PROPERTY_FILE_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getFileName() {
		return this.fileName;
	}

	/**
	 * Get fileSize
	 *
	 * @return fileSize
	 **/

	@JsonProperty(JSON_PROPERTY_FILE_SIZE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Integer getFileSize() {
		return this.fileSize;
	}

	/**
	 * Get sourceFileChecksum
	 *
	 * @return sourceFileChecksum
	 **/

	@JsonProperty(JSON_PROPERTY_SOURCE_FILE_CHECKSUM)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getSourceFileChecksum() {
		return this.sourceFileChecksum;
	}

	/**
	 * Get uploadOperations
	 *
	 * @return uploadOperations
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_UPLOAD_OPERATIONS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<UploadOperation> getUploadOperations() {
		return this.uploadOperations;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.fileSize, this.fileName, this.sourceFileChecksum, this.uploadOperations,
				this.assetDeliveryState);
	}

	public void setAssetDeliveryState(AppMediaAssetState assetDeliveryState) {
		this.assetDeliveryState = assetDeliveryState;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	public void setSourceFileChecksum(String sourceFileChecksum) {
		this.sourceFileChecksum = sourceFileChecksum;
	}

	public void setUploadOperations(List<UploadOperation> uploadOperations) {
		this.uploadOperations = uploadOperations;
	}

	public AppStoreReviewAttachmentAttributes sourceFileChecksum(String sourceFileChecksum) {

		this.sourceFileChecksum = sourceFileChecksum;
		return this;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppStoreReviewAttachmentAttributes {\n");
		sb.append("    fileSize: ").append(toIndentedString(this.fileSize)).append("\n");
		sb.append("    fileName: ").append(toIndentedString(this.fileName)).append("\n");
		sb.append("    sourceFileChecksum: ").append(toIndentedString(this.sourceFileChecksum)).append("\n");
		sb.append("    uploadOperations: ").append(toIndentedString(this.uploadOperations)).append("\n");
		sb.append("    assetDeliveryState: ").append(toIndentedString(this.assetDeliveryState)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	public AppStoreReviewAttachmentAttributes uploadOperations(List<UploadOperation> uploadOperations) {

		this.uploadOperations = uploadOperations;
		return this;
	}

}
