/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppUpdateRequestDataRelationships
 */
@JsonPropertyOrder({ AppUpdateRequestDataRelationships.JSON_PROPERTY_PRICES,
		AppUpdateRequestDataRelationships.JSON_PROPERTY_AVAILABLE_TERRITORIES })

public class AppUpdateRequestDataRelationships implements Serializable {
	public static final String JSON_PROPERTY_AVAILABLE_TERRITORIES = "availableTerritories";

	public static final String JSON_PROPERTY_PRICES = "prices";

	/**
	 *
	 */
	private static final long serialVersionUID = -5626263012781332971L;

	private AppUpdateRequestDataRelationshipsAvailableTerritories availableTerritories;
	private AppUpdateRequestDataRelationshipsPrices prices;

	public AppUpdateRequestDataRelationships availableTerritories(
			AppUpdateRequestDataRelationshipsAvailableTerritories availableTerritories) {

		this.availableTerritories = availableTerritories;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppUpdateRequestDataRelationships appUpdateRequestDataRelationships = (AppUpdateRequestDataRelationships) o;
		return Objects.equals(this.prices, appUpdateRequestDataRelationships.prices)
				&& Objects.equals(this.availableTerritories, appUpdateRequestDataRelationships.availableTerritories);
	}

	/**
	 * Get availableTerritories
	 *
	 * @return availableTerritories
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_AVAILABLE_TERRITORIES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppUpdateRequestDataRelationshipsAvailableTerritories getAvailableTerritories() {
		return this.availableTerritories;
	}

	/**
	 * Get prices
	 *
	 * @return prices
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_PRICES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppUpdateRequestDataRelationshipsPrices getPrices() {
		return this.prices;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.prices, this.availableTerritories);
	}

	public AppUpdateRequestDataRelationships prices(AppUpdateRequestDataRelationshipsPrices prices) {

		this.prices = prices;
		return this;
	}

	public void setAvailableTerritories(AppUpdateRequestDataRelationshipsAvailableTerritories availableTerritories) {
		this.availableTerritories = availableTerritories;
	}

	public void setPrices(AppUpdateRequestDataRelationshipsPrices prices) {
		this.prices = prices;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppUpdateRequestDataRelationships {\n");
		sb.append("    prices: ").append(toIndentedString(this.prices)).append("\n");
		sb.append("    availableTerritories: ").append(toIndentedString(this.availableTerritories)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
