/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AppUpdateRequestDataAttributes
 */
@JsonPropertyOrder({ AppUpdateRequestDataAttributes.JSON_PROPERTY_BUNDLE_ID,
		AppUpdateRequestDataAttributes.JSON_PROPERTY_PRIMARY_LOCALE,
		AppUpdateRequestDataAttributes.JSON_PROPERTY_AVAILABLE_IN_NEW_TERRITORIES,
		AppUpdateRequestDataAttributes.JSON_PROPERTY_CONTENT_RIGHTS_DECLARATION })

public class AppUpdateRequestDataAttributes implements Serializable {
	/**
	 * Gets or Sets contentRightsDeclaration
	 */
	public enum ContentRightsDeclarationEnum {
		DOES_NOT_USE_THIRD_PARTY_CONTENT("DOES_NOT_USE_THIRD_PARTY_CONTENT"),

		USES_THIRD_PARTY_CONTENT("USES_THIRD_PARTY_CONTENT");

		@JsonCreator
		public static ContentRightsDeclarationEnum fromValue(String value) {
			for (ContentRightsDeclarationEnum b : ContentRightsDeclarationEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			throw new IllegalArgumentException("Unexpected value '" + value + "'");
		}

		private String value;

		ContentRightsDeclarationEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return this.value;
		}

		@Override
		public String toString() {
			return String.valueOf(this.value);
		}
	}

	public static final String JSON_PROPERTY_AVAILABLE_IN_NEW_TERRITORIES = "availableInNewTerritories";

	public static final String JSON_PROPERTY_BUNDLE_ID = "bundleId";
	public static final String JSON_PROPERTY_CONTENT_RIGHTS_DECLARATION = "contentRightsDeclaration";

	public static final String JSON_PROPERTY_PRIMARY_LOCALE = "primaryLocale";
	/**
	 *
	 */
	private static final long serialVersionUID = 1018524054854593056L;

	private Boolean availableInNewTerritories;

	private String bundleId;

	private ContentRightsDeclarationEnum contentRightsDeclaration;
	private String primaryLocale;

	public AppUpdateRequestDataAttributes availableInNewTerritories(Boolean availableInNewTerritories) {

		this.availableInNewTerritories = availableInNewTerritories;
		return this;
	}

	public AppUpdateRequestDataAttributes bundleId(String bundleId) {

		this.bundleId = bundleId;
		return this;
	}

	public AppUpdateRequestDataAttributes contentRightsDeclaration(
			ContentRightsDeclarationEnum contentRightsDeclaration) {

		this.contentRightsDeclaration = contentRightsDeclaration;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppUpdateRequestDataAttributes appUpdateRequestDataAttributes = (AppUpdateRequestDataAttributes) o;
		return Objects.equals(this.bundleId, appUpdateRequestDataAttributes.bundleId)
				&& Objects.equals(this.primaryLocale, appUpdateRequestDataAttributes.primaryLocale)
				&& Objects.equals(this.availableInNewTerritories,
						appUpdateRequestDataAttributes.availableInNewTerritories)
				&& Objects.equals(this.contentRightsDeclaration,
						appUpdateRequestDataAttributes.contentRightsDeclaration);
	}

	/**
	 * Get availableInNewTerritories
	 *
	 * @return availableInNewTerritories
	 **/

	@JsonProperty(JSON_PROPERTY_AVAILABLE_IN_NEW_TERRITORIES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getAvailableInNewTerritories() {
		return this.availableInNewTerritories;
	}

	/**
	 * Get bundleId
	 *
	 * @return bundleId
	 **/

	@JsonProperty(JSON_PROPERTY_BUNDLE_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getBundleId() {
		return this.bundleId;
	}

	/**
	 * Get contentRightsDeclaration
	 *
	 * @return contentRightsDeclaration
	 **/

	@JsonProperty(JSON_PROPERTY_CONTENT_RIGHTS_DECLARATION)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public ContentRightsDeclarationEnum getContentRightsDeclaration() {
		return this.contentRightsDeclaration;
	}

	/**
	 * Get primaryLocale
	 *
	 * @return primaryLocale
	 **/

	@JsonProperty(JSON_PROPERTY_PRIMARY_LOCALE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getPrimaryLocale() {
		return this.primaryLocale;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.bundleId, this.primaryLocale, this.availableInNewTerritories,
				this.contentRightsDeclaration);
	}

	public AppUpdateRequestDataAttributes primaryLocale(String primaryLocale) {

		this.primaryLocale = primaryLocale;
		return this;
	}

	public void setAvailableInNewTerritories(Boolean availableInNewTerritories) {
		this.availableInNewTerritories = availableInNewTerritories;
	}

	public void setBundleId(String bundleId) {
		this.bundleId = bundleId;
	}

	public void setContentRightsDeclaration(ContentRightsDeclarationEnum contentRightsDeclaration) {
		this.contentRightsDeclaration = contentRightsDeclaration;
	}

	public void setPrimaryLocale(String primaryLocale) {
		this.primaryLocale = primaryLocale;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppUpdateRequestDataAttributes {\n");
		sb.append("    bundleId: ").append(toIndentedString(this.bundleId)).append("\n");
		sb.append("    primaryLocale: ").append(toIndentedString(this.primaryLocale)).append("\n");
		sb.append("    availableInNewTerritories: ").append(toIndentedString(this.availableInNewTerritories))
				.append("\n");
		sb.append("    contentRightsDeclaration: ").append(toIndentedString(this.contentRightsDeclaration))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

}
