/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BetaTesterInvitationCreateRequestDataRelationships
 */
@JsonPropertyOrder({ BetaTesterInvitationCreateRequestDataRelationships.JSON_PROPERTY_BETA_TESTER,
		BetaTesterInvitationCreateRequestDataRelationships.JSON_PROPERTY_APP })

public class BetaTesterInvitationCreateRequestDataRelationships implements Serializable {
	public static final String JSON_PROPERTY_APP = "app";

	public static final String JSON_PROPERTY_BETA_TESTER = "betaTester";

	/**
	 *
	 */
	private static final long serialVersionUID = 1602785869675983539L;

	private AppPreOrderCreateRequestDataRelationshipsApp app;
	private BetaTesterInvitationCreateRequestDataRelationshipsBetaTester betaTester;

	public BetaTesterInvitationCreateRequestDataRelationships app(AppPreOrderCreateRequestDataRelationshipsApp app) {

		this.app = app;
		return this;
	}

	public BetaTesterInvitationCreateRequestDataRelationships betaTester(
			BetaTesterInvitationCreateRequestDataRelationshipsBetaTester betaTester) {

		this.betaTester = betaTester;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BetaTesterInvitationCreateRequestDataRelationships betaTesterInvitationCreateRequestDataRelationships = (BetaTesterInvitationCreateRequestDataRelationships) o;
		return Objects.equals(this.betaTester, betaTesterInvitationCreateRequestDataRelationships.betaTester)
				&& Objects.equals(this.app, betaTesterInvitationCreateRequestDataRelationships.app);
	}

	/**
	 * Get app
	 *
	 * @return app
	 **/
	@NotNull
	@Valid

	@JsonProperty(JSON_PROPERTY_APP)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public AppPreOrderCreateRequestDataRelationshipsApp getApp() {
		return this.app;
	}

	/**
	 * Get betaTester
	 *
	 * @return betaTester
	 **/
	@NotNull
	@Valid

	@JsonProperty(JSON_PROPERTY_BETA_TESTER)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public BetaTesterInvitationCreateRequestDataRelationshipsBetaTester getBetaTester() {
		return this.betaTester;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.betaTester, this.app);
	}

	public void setApp(AppPreOrderCreateRequestDataRelationshipsApp app) {
		this.app = app;
	}

	public void setBetaTester(BetaTesterInvitationCreateRequestDataRelationshipsBetaTester betaTester) {
		this.betaTester = betaTester;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BetaTesterInvitationCreateRequestDataRelationships {\n");
		sb.append("    betaTester: ").append(toIndentedString(this.betaTester)).append("\n");
		sb.append("    app: ").append(toIndentedString(this.app)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
