/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BetaTesterRelationships
 */
@JsonPropertyOrder({ BetaTesterRelationships.JSON_PROPERTY_APPS, BetaTesterRelationships.JSON_PROPERTY_BETA_GROUPS,
		BetaTesterRelationships.JSON_PROPERTY_BUILDS })

public class BetaTesterRelationships implements Serializable {
	public static final String JSON_PROPERTY_APPS = "apps";

	public static final String JSON_PROPERTY_BETA_GROUPS = "betaGroups";

	public static final String JSON_PROPERTY_BUILDS = "builds";
	/**
	 *
	 */
	private static final long serialVersionUID = 2123465817615739943L;

	private BetaTesterRelationshipsApps apps;

	private AppRelationshipsBetaGroups betaGroups;
	private AppRelationshipsBuilds builds;

	public BetaTesterRelationships apps(BetaTesterRelationshipsApps apps) {

		this.apps = apps;
		return this;
	}

	public BetaTesterRelationships betaGroups(AppRelationshipsBetaGroups betaGroups) {

		this.betaGroups = betaGroups;
		return this;
	}

	public BetaTesterRelationships builds(AppRelationshipsBuilds builds) {

		this.builds = builds;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BetaTesterRelationships betaTesterRelationships = (BetaTesterRelationships) o;
		return Objects.equals(this.apps, betaTesterRelationships.apps)
				&& Objects.equals(this.betaGroups, betaTesterRelationships.betaGroups)
				&& Objects.equals(this.builds, betaTesterRelationships.builds);
	}

	/**
	 * Get apps
	 *
	 * @return apps
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_APPS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public BetaTesterRelationshipsApps getApps() {
		return this.apps;
	}

	/**
	 * Get betaGroups
	 *
	 * @return betaGroups
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_BETA_GROUPS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppRelationshipsBetaGroups getBetaGroups() {
		return this.betaGroups;
	}

	/**
	 * Get builds
	 *
	 * @return builds
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_BUILDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppRelationshipsBuilds getBuilds() {
		return this.builds;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.apps, this.betaGroups, this.builds);
	}

	public void setApps(BetaTesterRelationshipsApps apps) {
		this.apps = apps;
	}

	public void setBetaGroups(AppRelationshipsBetaGroups betaGroups) {
		this.betaGroups = betaGroups;
	}

	public void setBuilds(AppRelationshipsBuilds builds) {
		this.builds = builds;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BetaTesterRelationships {\n");
		sb.append("    apps: ").append(toIndentedString(this.apps)).append("\n");
		sb.append("    betaGroups: ").append(toIndentedString(this.betaGroups)).append("\n");
		sb.append("    builds: ").append(toIndentedString(this.builds)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
