/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BetaAppReviewSubmissionRelationships
 */
@JsonPropertyOrder({ BetaAppReviewSubmissionRelationships.JSON_PROPERTY_BUILD })

public class BetaAppReviewSubmissionRelationships implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -5967473912983158310L;

	public static final String JSON_PROPERTY_BUILD = "build";

	private AppStoreVersionRelationshipsBuild build;

	public BetaAppReviewSubmissionRelationships build(AppStoreVersionRelationshipsBuild build) {

		this.build = build;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BetaAppReviewSubmissionRelationships betaAppReviewSubmissionRelationships = (BetaAppReviewSubmissionRelationships) o;
		return Objects.equals(this.build, betaAppReviewSubmissionRelationships.build);
	}

	/**
	 * Get build
	 *
	 * @return build
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_BUILD)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppStoreVersionRelationshipsBuild getBuild() {
		return this.build;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.build);
	}

	public void setBuild(AppStoreVersionRelationshipsBuild build) {
		this.build = build;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BetaAppReviewSubmissionRelationships {\n");
		sb.append("    build: ").append(toIndentedString(this.build)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
