/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BetaTesterCreateRequestDataRelationships
 */
@JsonPropertyOrder({ BetaTesterCreateRequestDataRelationships.JSON_PROPERTY_BETA_GROUPS,
		BetaTesterCreateRequestDataRelationships.JSON_PROPERTY_BUILDS })

public class BetaTesterCreateRequestDataRelationships implements Serializable {
	public static final String JSON_PROPERTY_BETA_GROUPS = "betaGroups";

	public static final String JSON_PROPERTY_BUILDS = "builds";

	/**
	 *
	 */
	private static final long serialVersionUID = -8178232481425361579L;

	private BetaTesterCreateRequestDataRelationshipsBetaGroups betaGroups;
	private BetaGroupCreateRequestDataRelationshipsBuilds builds;

	public BetaTesterCreateRequestDataRelationships betaGroups(
			BetaTesterCreateRequestDataRelationshipsBetaGroups betaGroups) {

		this.betaGroups = betaGroups;
		return this;
	}

	public BetaTesterCreateRequestDataRelationships builds(BetaGroupCreateRequestDataRelationshipsBuilds builds) {

		this.builds = builds;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BetaTesterCreateRequestDataRelationships betaTesterCreateRequestDataRelationships = (BetaTesterCreateRequestDataRelationships) o;
		return Objects.equals(this.betaGroups, betaTesterCreateRequestDataRelationships.betaGroups)
				&& Objects.equals(this.builds, betaTesterCreateRequestDataRelationships.builds);
	}

	/**
	 * Get betaGroups
	 *
	 * @return betaGroups
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_BETA_GROUPS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public BetaTesterCreateRequestDataRelationshipsBetaGroups getBetaGroups() {
		return this.betaGroups;
	}

	/**
	 * Get builds
	 *
	 * @return builds
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_BUILDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public BetaGroupCreateRequestDataRelationshipsBuilds getBuilds() {
		return this.builds;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.betaGroups, this.builds);
	}

	public void setBetaGroups(BetaTesterCreateRequestDataRelationshipsBetaGroups betaGroups) {
		this.betaGroups = betaGroups;
	}

	public void setBuilds(BetaGroupCreateRequestDataRelationshipsBuilds builds) {
		this.builds = builds;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BetaTesterCreateRequestDataRelationships {\n");
		sb.append("    betaGroups: ").append(toIndentedString(this.betaGroups)).append("\n");
		sb.append("    builds: ").append(toIndentedString(this.builds)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
