/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BundleIdCreateRequestDataAttributes
 */
@JsonPropertyOrder({ BundleIdCreateRequestDataAttributes.JSON_PROPERTY_NAME,
		BundleIdCreateRequestDataAttributes.JSON_PROPERTY_PLATFORM,
		BundleIdCreateRequestDataAttributes.JSON_PROPERTY_IDENTIFIER,
		BundleIdCreateRequestDataAttributes.JSON_PROPERTY_SEED_ID })

public class BundleIdCreateRequestDataAttributes implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -5426905370542421614L;

	public static final String JSON_PROPERTY_IDENTIFIER = "identifier";

	public static final String JSON_PROPERTY_NAME = "name";
	public static final String JSON_PROPERTY_PLATFORM = "platform";

	public static final String JSON_PROPERTY_SEED_ID = "seedId";

	private String identifier;
	private String name;

	private BundleIdPlatform platform;
	private String seedId;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BundleIdCreateRequestDataAttributes bundleIdCreateRequestDataAttributes = (BundleIdCreateRequestDataAttributes) o;
		return Objects.equals(this.name, bundleIdCreateRequestDataAttributes.name)
				&& Objects.equals(this.platform, bundleIdCreateRequestDataAttributes.platform)
				&& Objects.equals(this.identifier, bundleIdCreateRequestDataAttributes.identifier)
				&& Objects.equals(this.seedId, bundleIdCreateRequestDataAttributes.seedId);
	}

	/**
	 * Get identifier
	 *
	 * @return identifier
	 **/
	@NotNull

	@JsonProperty(JSON_PROPERTY_IDENTIFIER)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public String getIdentifier() {
		return this.identifier;
	}

	/**
	 * Get name
	 *
	 * @return name
	 **/
	@NotNull

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public String getName() {
		return this.name;
	}

	/**
	 * Get platform
	 *
	 * @return platform
	 **/
	@NotNull
	@Valid

	@JsonProperty(JSON_PROPERTY_PLATFORM)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public BundleIdPlatform getPlatform() {
		return this.platform;
	}

	/**
	 * Get seedId
	 *
	 * @return seedId
	 **/

	@JsonProperty(JSON_PROPERTY_SEED_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getSeedId() {
		return this.seedId;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.name, this.platform, this.identifier, this.seedId);
	}

	public BundleIdCreateRequestDataAttributes identifier(String identifier) {

		this.identifier = identifier;
		return this;
	}

	public BundleIdCreateRequestDataAttributes name(String name) {

		this.name = name;
		return this;
	}

	public BundleIdCreateRequestDataAttributes platform(BundleIdPlatform platform) {

		this.platform = platform;
		return this;
	}

	public BundleIdCreateRequestDataAttributes seedId(String seedId) {

		this.seedId = seedId;
		return this;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPlatform(BundleIdPlatform platform) {
		this.platform = platform;
	}

	public void setSeedId(String seedId) {
		this.seedId = seedId;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BundleIdCreateRequestDataAttributes {\n");
		sb.append("    name: ").append(toIndentedString(this.name)).append("\n");
		sb.append("    platform: ").append(toIndentedString(this.platform)).append("\n");
		sb.append("    identifier: ").append(toIndentedString(this.identifier)).append("\n");
		sb.append("    seedId: ").append(toIndentedString(this.seedId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
