/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BundleIdRelationships
 */
@JsonPropertyOrder({ BundleIdRelationships.JSON_PROPERTY_PROFILES,
		BundleIdRelationships.JSON_PROPERTY_BUNDLE_ID_CAPABILITIES, BundleIdRelationships.JSON_PROPERTY_APP })

public class BundleIdRelationships implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -6950987938050482553L;

	public static final String JSON_PROPERTY_APP = "app";

	public static final String JSON_PROPERTY_BUNDLE_ID_CAPABILITIES = "bundleIdCapabilities";
	public static final String JSON_PROPERTY_PROFILES = "profiles";

	private AppEncryptionDeclarationRelationshipsApp app;

	private BundleIdRelationshipsBundleIdCapabilities bundleIdCapabilities;
	private BundleIdRelationshipsProfiles profiles;

	public BundleIdRelationships app(AppEncryptionDeclarationRelationshipsApp app) {

		this.app = app;
		return this;
	}

	public BundleIdRelationships bundleIdCapabilities(BundleIdRelationshipsBundleIdCapabilities bundleIdCapabilities) {

		this.bundleIdCapabilities = bundleIdCapabilities;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BundleIdRelationships bundleIdRelationships = (BundleIdRelationships) o;
		return Objects.equals(this.profiles, bundleIdRelationships.profiles)
				&& Objects.equals(this.bundleIdCapabilities, bundleIdRelationships.bundleIdCapabilities)
				&& Objects.equals(this.app, bundleIdRelationships.app);
	}

	/**
	 * Get app
	 *
	 * @return app
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_APP)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppEncryptionDeclarationRelationshipsApp getApp() {
		return this.app;
	}

	/**
	 * Get bundleIdCapabilities
	 *
	 * @return bundleIdCapabilities
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_BUNDLE_ID_CAPABILITIES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public BundleIdRelationshipsBundleIdCapabilities getBundleIdCapabilities() {
		return this.bundleIdCapabilities;
	}

	/**
	 * Get profiles
	 *
	 * @return profiles
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_PROFILES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public BundleIdRelationshipsProfiles getProfiles() {
		return this.profiles;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.profiles, this.bundleIdCapabilities, this.app);
	}

	public BundleIdRelationships profiles(BundleIdRelationshipsProfiles profiles) {

		this.profiles = profiles;
		return this;
	}

	public void setApp(AppEncryptionDeclarationRelationshipsApp app) {
		this.app = app;
	}

	public void setBundleIdCapabilities(BundleIdRelationshipsBundleIdCapabilities bundleIdCapabilities) {
		this.bundleIdCapabilities = bundleIdCapabilities;
	}

	public void setProfiles(BundleIdRelationshipsProfiles profiles) {
		this.profiles = profiles;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BundleIdRelationships {\n");
		sb.append("    profiles: ").append(toIndentedString(this.profiles)).append("\n");
		sb.append("    bundleIdCapabilities: ").append(toIndentedString(this.bundleIdCapabilities)).append("\n");
		sb.append("    app: ").append(toIndentedString(this.app)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
