/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * EndUserLicenseAgreementRelationships
 */
@JsonPropertyOrder({ EndUserLicenseAgreementRelationships.JSON_PROPERTY_APP,
		EndUserLicenseAgreementRelationships.JSON_PROPERTY_TERRITORIES })

public class EndUserLicenseAgreementRelationships implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -2566980940104868553L;

	public static final String JSON_PROPERTY_APP = "app";

	public static final String JSON_PROPERTY_TERRITORIES = "territories";

	private AppEncryptionDeclarationRelationshipsApp app;
	private AppRelationshipsAvailableTerritories territories;

	public EndUserLicenseAgreementRelationships app(AppEncryptionDeclarationRelationshipsApp app) {

		this.app = app;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EndUserLicenseAgreementRelationships endUserLicenseAgreementRelationships = (EndUserLicenseAgreementRelationships) o;
		return Objects.equals(this.app, endUserLicenseAgreementRelationships.app)
				&& Objects.equals(this.territories, endUserLicenseAgreementRelationships.territories);
	}

	/**
	 * Get app
	 *
	 * @return app
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_APP)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppEncryptionDeclarationRelationshipsApp getApp() {
		return this.app;
	}

	/**
	 * Get territories
	 *
	 * @return territories
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_TERRITORIES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppRelationshipsAvailableTerritories getTerritories() {
		return this.territories;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.app, this.territories);
	}

	public void setApp(AppEncryptionDeclarationRelationshipsApp app) {
		this.app = app;
	}

	public void setTerritories(AppRelationshipsAvailableTerritories territories) {
		this.territories = territories;
	}

	public EndUserLicenseAgreementRelationships territories(AppRelationshipsAvailableTerritories territories) {

		this.territories = territories;
		return this;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EndUserLicenseAgreementRelationships {\n");
		sb.append("    app: ").append(toIndentedString(this.app)).append("\n");
		sb.append("    territories: ").append(toIndentedString(this.territories)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
