/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * EndUserLicenseAgreementUpdateRequestDataRelationships
 */
@JsonPropertyOrder({ EndUserLicenseAgreementUpdateRequestDataRelationships.JSON_PROPERTY_TERRITORIES })

public class EndUserLicenseAgreementUpdateRequestDataRelationships implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 8076079345696031492L;

	public static final String JSON_PROPERTY_TERRITORIES = "territories";

	private AppUpdateRequestDataRelationshipsAvailableTerritories territories;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EndUserLicenseAgreementUpdateRequestDataRelationships endUserLicenseAgreementUpdateRequestDataRelationships = (EndUserLicenseAgreementUpdateRequestDataRelationships) o;
		return Objects.equals(this.territories, endUserLicenseAgreementUpdateRequestDataRelationships.territories);
	}

	/**
	 * Get territories
	 *
	 * @return territories
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_TERRITORIES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public AppUpdateRequestDataRelationshipsAvailableTerritories getTerritories() {
		return this.territories;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.territories);
	}

	public void setTerritories(AppUpdateRequestDataRelationshipsAvailableTerritories territories) {
		this.territories = territories;
	}

	public EndUserLicenseAgreementUpdateRequestDataRelationships territories(
			AppUpdateRequestDataRelationshipsAvailableTerritories territories) {

		this.territories = territories;
		return this;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EndUserLicenseAgreementUpdateRequestDataRelationships {\n");
		sb.append("    territories: ").append(toIndentedString(this.territories)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
