/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PrereleaseVersionAttributes
 */
@JsonPropertyOrder({ PrereleaseVersionAttributes.JSON_PROPERTY_VERSION,
		PrereleaseVersionAttributes.JSON_PROPERTY_PLATFORM })

public class PrereleaseVersionAttributes implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -867564088459803830L;

	public static final String JSON_PROPERTY_PLATFORM = "platform";

	public static final String JSON_PROPERTY_VERSION = "version";

	private Platform platform;
	private String version;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PrereleaseVersionAttributes prereleaseVersionAttributes = (PrereleaseVersionAttributes) o;
		return Objects.equals(this.version, prereleaseVersionAttributes.version)
				&& Objects.equals(this.platform, prereleaseVersionAttributes.platform);
	}

	/**
	 * Get platform
	 *
	 * @return platform
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_PLATFORM)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Platform getPlatform() {
		return this.platform;
	}

	/**
	 * Get version
	 *
	 * @return version
	 **/

	@JsonProperty(JSON_PROPERTY_VERSION)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getVersion() {
		return this.version;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.version, this.platform);
	}

	public PrereleaseVersionAttributes platform(Platform platform) {

		this.platform = platform;
		return this;
	}

	public void setPlatform(Platform platform) {
		this.platform = platform;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PrereleaseVersionAttributes {\n");
		sb.append("    version: ").append(toIndentedString(this.version)).append("\n");
		sb.append("    platform: ").append(toIndentedString(this.platform)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	public PrereleaseVersionAttributes version(String version) {

		this.version = version;
		return this;
	}

}
