/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ProfileCreateRequestDataAttributes
 */
@JsonPropertyOrder({ ProfileCreateRequestDataAttributes.JSON_PROPERTY_NAME,
		ProfileCreateRequestDataAttributes.JSON_PROPERTY_PROFILE_TYPE })

public class ProfileCreateRequestDataAttributes implements Serializable {
	/**
	 * Gets or Sets profileType
	 */
	public enum ProfileTypeEnum {
		IOS_APP_ADHOC("IOS_APP_ADHOC"),

		IOS_APP_DEVELOPMENT("IOS_APP_DEVELOPMENT"),

		IOS_APP_INHOUSE("IOS_APP_INHOUSE"),

		IOS_APP_STORE("IOS_APP_STORE"),

		MAC_APP_DEVELOPMENT("MAC_APP_DEVELOPMENT"),

		MAC_APP_DIRECT("MAC_APP_DIRECT"),

		MAC_APP_STORE("MAC_APP_STORE"),

		MAC_CATALYST_APP_DEVELOPMENT("MAC_CATALYST_APP_DEVELOPMENT"),

		MAC_CATALYST_APP_DIRECT("MAC_CATALYST_APP_DIRECT"),

		MAC_CATALYST_APP_STORE("MAC_CATALYST_APP_STORE"),

		TVOS_APP_ADHOC("TVOS_APP_ADHOC"),

		TVOS_APP_DEVELOPMENT("TVOS_APP_DEVELOPMENT"),

		TVOS_APP_INHOUSE("TVOS_APP_INHOUSE"),

		TVOS_APP_STORE("TVOS_APP_STORE");

		@JsonCreator
		public static ProfileTypeEnum fromValue(String value) {
			for (ProfileTypeEnum b : ProfileTypeEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			throw new IllegalArgumentException("Unexpected value '" + value + "'");
		}

		private String value;

		ProfileTypeEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return this.value;
		}

		@Override
		public String toString() {
			return String.valueOf(this.value);
		}
	}

	public static final String JSON_PROPERTY_NAME = "name";

	public static final String JSON_PROPERTY_PROFILE_TYPE = "profileType";
	/**
	 *
	 */
	private static final long serialVersionUID = 1956082677379033974L;

	private String name;
	private ProfileTypeEnum profileType;

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ProfileCreateRequestDataAttributes profileCreateRequestDataAttributes = (ProfileCreateRequestDataAttributes) o;
		return Objects.equals(this.name, profileCreateRequestDataAttributes.name)
				&& Objects.equals(this.profileType, profileCreateRequestDataAttributes.profileType);
	}

	/**
	 * Get name
	 *
	 * @return name
	 **/
	@NotNull

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public String getName() {
		return this.name;
	}

	/**
	 * Get profileType
	 *
	 * @return profileType
	 **/
	@NotNull

	@JsonProperty(JSON_PROPERTY_PROFILE_TYPE)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public ProfileTypeEnum getProfileType() {
		return this.profileType;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.name, this.profileType);
	}

	public ProfileCreateRequestDataAttributes name(String name) {

		this.name = name;
		return this;
	}

	public ProfileCreateRequestDataAttributes profileType(ProfileTypeEnum profileType) {

		this.profileType = profileType;
		return this;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setProfileType(ProfileTypeEnum profileType) {
		this.profileType = profileType;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ProfileCreateRequestDataAttributes {\n");
		sb.append("    name: ").append(toIndentedString(this.name)).append("\n");
		sb.append("    profileType: ").append(toIndentedString(this.profileType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
