/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UserAttributes
 */
@JsonPropertyOrder({ UserAttributes.JSON_PROPERTY_USERNAME, UserAttributes.JSON_PROPERTY_FIRST_NAME,
		UserAttributes.JSON_PROPERTY_LAST_NAME, UserAttributes.JSON_PROPERTY_ROLES,
		UserAttributes.JSON_PROPERTY_ALL_APPS_VISIBLE, UserAttributes.JSON_PROPERTY_PROVISIONING_ALLOWED })

public class UserAttributes implements Serializable {
	public static final String JSON_PROPERTY_ALL_APPS_VISIBLE = "allAppsVisible";

	public static final String JSON_PROPERTY_FIRST_NAME = "firstName";

	public static final String JSON_PROPERTY_LAST_NAME = "lastName";
	public static final String JSON_PROPERTY_PROVISIONING_ALLOWED = "provisioningAllowed";

	public static final String JSON_PROPERTY_ROLES = "roles";
	public static final String JSON_PROPERTY_USERNAME = "username";

	/**
	 *
	 */
	private static final long serialVersionUID = 8495646094251431443L;

	private Boolean allAppsVisible;
	private String firstName;

	private String lastName;
	private Boolean provisioningAllowed;

	private List<UserRole> roles = null;
	private String username;

	public UserAttributes addRolesItem(UserRole rolesItem) {
		if (this.roles == null) {
			this.roles = new ArrayList<>();
		}
		this.roles.add(rolesItem);
		return this;
	}

	public UserAttributes allAppsVisible(Boolean allAppsVisible) {

		this.allAppsVisible = allAppsVisible;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UserAttributes userAttributes = (UserAttributes) o;
		return Objects.equals(this.username, userAttributes.username)
				&& Objects.equals(this.firstName, userAttributes.firstName)
				&& Objects.equals(this.lastName, userAttributes.lastName)
				&& Objects.equals(this.roles, userAttributes.roles)
				&& Objects.equals(this.allAppsVisible, userAttributes.allAppsVisible)
				&& Objects.equals(this.provisioningAllowed, userAttributes.provisioningAllowed);
	}

	public UserAttributes firstName(String firstName) {

		this.firstName = firstName;
		return this;
	}

	/**
	 * Get allAppsVisible
	 *
	 * @return allAppsVisible
	 **/

	@JsonProperty(JSON_PROPERTY_ALL_APPS_VISIBLE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getAllAppsVisible() {
		return this.allAppsVisible;
	}

	/**
	 * Get firstName
	 *
	 * @return firstName
	 **/

	@JsonProperty(JSON_PROPERTY_FIRST_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getFirstName() {
		return this.firstName;
	}

	/**
	 * Get lastName
	 *
	 * @return lastName
	 **/

	@JsonProperty(JSON_PROPERTY_LAST_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getLastName() {
		return this.lastName;
	}

	/**
	 * Get provisioningAllowed
	 *
	 * @return provisioningAllowed
	 **/

	@JsonProperty(JSON_PROPERTY_PROVISIONING_ALLOWED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getProvisioningAllowed() {
		return this.provisioningAllowed;
	}

	/**
	 * Get roles
	 *
	 * @return roles
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_ROLES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<UserRole> getRoles() {
		return this.roles;
	}

	/**
	 * Get username
	 *
	 * @return username
	 **/

	@JsonProperty(JSON_PROPERTY_USERNAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getUsername() {
		return this.username;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.username, this.firstName, this.lastName, this.roles, this.allAppsVisible,
				this.provisioningAllowed);
	}

	public UserAttributes lastName(String lastName) {

		this.lastName = lastName;
		return this;
	}

	public UserAttributes provisioningAllowed(Boolean provisioningAllowed) {

		this.provisioningAllowed = provisioningAllowed;
		return this;
	}

	public UserAttributes roles(List<UserRole> roles) {

		this.roles = roles;
		return this;
	}

	public void setAllAppsVisible(Boolean allAppsVisible) {
		this.allAppsVisible = allAppsVisible;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setProvisioningAllowed(Boolean provisioningAllowed) {
		this.provisioningAllowed = provisioningAllowed;
	}

	public void setRoles(List<UserRole> roles) {
		this.roles = roles;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class UserAttributes {\n");
		sb.append("    username: ").append(toIndentedString(this.username)).append("\n");
		sb.append("    firstName: ").append(toIndentedString(this.firstName)).append("\n");
		sb.append("    lastName: ").append(toIndentedString(this.lastName)).append("\n");
		sb.append("    roles: ").append(toIndentedString(this.roles)).append("\n");
		sb.append("    allAppsVisible: ").append(toIndentedString(this.allAppsVisible)).append("\n");
		sb.append("    provisioningAllowed: ").append(toIndentedString(this.provisioningAllowed)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	public UserAttributes username(String username) {

		this.username = username;
		return this;
	}

}
