/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets UserRole
 */
public enum UserRole {

	ACCESS_TO_REPORTS("ACCESS_TO_REPORTS"),

	ACCOUNT_HOLDER("ACCOUNT_HOLDER"),

	ADMIN("ADMIN"),

	APP_MANAGER("APP_MANAGER"),

	CUSTOMER_SUPPORT("CUSTOMER_SUPPORT"),

	DEVELOPER("DEVELOPER"),

	FINANCE("FINANCE"),

	MARKETING("MARKETING"),

	READ_ONLY("READ_ONLY"),

	SALES("SALES"),

	TECHNICAL("TECHNICAL");

	@JsonCreator
	public static UserRole fromValue(String value) {
		for (UserRole b : UserRole.values()) {
			if (b.value.equals(value)) {
				return b;
			}
		}
		throw new IllegalArgumentException("Unexpected value '" + value + "'");
	}

	private String value;

	UserRole(String value) {
		this.value = value;
	}

	@JsonValue
	public String getValue() {
		return this.value;
	}

	@Override
	public String toString() {
		return String.valueOf(this.value);
	}
}
