/*
 * App Store Connect API
 * Automate the tasks you perform on the Apple Developer website and in App Store Connect.  The App Store Connect API is a REST API that enables the automation of actions you take in App Store Connect.  Calls to the API require JSON Web Tokens (JWT) for authorization; you obtain keys to create the tokens from your organization’s App Store Connect account.
 *
 * The version of the OpenAPI document: 1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.odyssi.asc4j.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UserUpdateRequestDataAttributes
 */
@JsonPropertyOrder({ UserUpdateRequestDataAttributes.JSON_PROPERTY_ROLES,
		UserUpdateRequestDataAttributes.JSON_PROPERTY_ALL_APPS_VISIBLE,
		UserUpdateRequestDataAttributes.JSON_PROPERTY_PROVISIONING_ALLOWED })

public class UserUpdateRequestDataAttributes implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 6856114446533530988L;

	public static final String JSON_PROPERTY_ALL_APPS_VISIBLE = "allAppsVisible";

	public static final String JSON_PROPERTY_PROVISIONING_ALLOWED = "provisioningAllowed";
	public static final String JSON_PROPERTY_ROLES = "roles";

	private Boolean allAppsVisible;

	private Boolean provisioningAllowed;
	private List<UserRole> roles = null;

	public UserUpdateRequestDataAttributes addRolesItem(UserRole rolesItem) {
		if (this.roles == null) {
			this.roles = new ArrayList<>();
		}
		this.roles.add(rolesItem);
		return this;
	}

	public UserUpdateRequestDataAttributes allAppsVisible(Boolean allAppsVisible) {

		this.allAppsVisible = allAppsVisible;
		return this;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UserUpdateRequestDataAttributes userUpdateRequestDataAttributes = (UserUpdateRequestDataAttributes) o;
		return Objects.equals(this.roles, userUpdateRequestDataAttributes.roles)
				&& Objects.equals(this.allAppsVisible, userUpdateRequestDataAttributes.allAppsVisible)
				&& Objects.equals(this.provisioningAllowed, userUpdateRequestDataAttributes.provisioningAllowed);
	}

	/**
	 * Get allAppsVisible
	 *
	 * @return allAppsVisible
	 **/

	@JsonProperty(JSON_PROPERTY_ALL_APPS_VISIBLE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getAllAppsVisible() {
		return this.allAppsVisible;
	}

	/**
	 * Get provisioningAllowed
	 *
	 * @return provisioningAllowed
	 **/

	@JsonProperty(JSON_PROPERTY_PROVISIONING_ALLOWED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getProvisioningAllowed() {
		return this.provisioningAllowed;
	}

	/**
	 * Get roles
	 *
	 * @return roles
	 **/

	@Valid

	@JsonProperty(JSON_PROPERTY_ROLES)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<UserRole> getRoles() {
		return this.roles;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.roles, this.allAppsVisible, this.provisioningAllowed);
	}

	public UserUpdateRequestDataAttributes provisioningAllowed(Boolean provisioningAllowed) {

		this.provisioningAllowed = provisioningAllowed;
		return this;
	}

	public UserUpdateRequestDataAttributes roles(List<UserRole> roles) {

		this.roles = roles;
		return this;
	}

	public void setAllAppsVisible(Boolean allAppsVisible) {
		this.allAppsVisible = allAppsVisible;
	}

	public void setProvisioningAllowed(Boolean provisioningAllowed) {
		this.provisioningAllowed = provisioningAllowed;
	}

	public void setRoles(List<UserRole> roles) {
		this.roles = roles;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class UserUpdateRequestDataAttributes {\n");
		sb.append("    roles: ").append(toIndentedString(this.roles)).append("\n");
		sb.append("    allAppsVisible: ").append(toIndentedString(this.allAppsVisible)).append("\n");
		sb.append("    provisioningAllowed: ").append(toIndentedString(this.provisioningAllowed)).append("\n");
		sb.append("}");
		return sb.toString();
	}

}
